### ISSUE TITLE
Argon2 support

### ISSUE THREAD

**Issue by F21** [hlandau/passlib#4]
Are there any plans for argon2 support? I think it would be a great addition to the library :smiley:

**Comment by ErwanLegrand** [comment]
Argon2i should definitely be the default. As it won the Password Hashing Competition, it is to password hashing functions what Rijndael/AES is to block ciphers.

**Comment by F21** [comment]
Argon2 has landed in `x/crypto`! https://godoc.org/golang.org/x/crypto/argon2
