### ISSUE TITLE
Password migration?

### ISSUE THREAD

**Issue by Schnouki** [hlandau/passlib#5]
First of all, thanks for this package! No nonsense, works as expected, and easy to extend. 👍 

For an app I'm working on, I wrote a small wrapper for the [phpass](https://github.com/apokalyptik/phpass) package (used to authenticate users after a migration from Wordpress). However I'd also *love* to be able to migrate those users to more secure password hashes transparently as they sign in. But at the moment, `Verify()` only returns new hashes computed with the same algorithm as the "old" one.

So would it be possible to either:
- add a global (per-context) flag to "force" upgrading old hashes to the first in the context schemes?
- or add a `DeprecatedSchemes` field to the passlib context that contain schemes that can be used to check passwords, but which will always trigger an upgrade to one in the normal `Schemes`?

IMO the latter would be nicer. It's also similar to [what the Python passlib does](https://pythonhosted.org/passlib/lib/passlib.context-tutorial.html#deprecation-hash-migration). What do you think? (I'm interested in writing a patch myself to implement whichever you prefer...)

**Comment by hlandau** [comment]
Verify certainly should be returning new hashes which use a new algorithm. It's designed to rehash if the scheme-specific information is considered inadequate, or if the scheme used isn't the first in the context array: https://github.com/hlandau/passlib/blob/v1.0.8/passlib.go#L106

**Comment by hlandau** [comment]
There was a slight bug in NeedsUpdate, I've tagged a fix in v1.0.9. Let me know if you continue to have issues.

**Comment by Schnouki** [comment]
Awesome! It works :) Thanks a lot for the quick answer and quick fix.
