### ISSUE TITLE
Example of how to change the hashing scheme from user code

### ISSUE THREAD

**Issue by kuchlous** [hlandau/passlib#6]
Can you please provide a simple example of how to change the hashing scheme preference from the user code. I am trying to create a Context with different order but as soon as I import the hashing packages, I start getting duplicate exported symbol errors.

**Comment by hlandau** [comment]
@kuchlous Please elaborate with pastes of errors? This should work:

```go
import (
  "gopkg.in/hlandau/passlib.v1"
  "gopkg.in/hlandau/passlib.v1/abstract"
  "gopkg.in/hlandau/passlib.v1/hash/argon2"
)

func Foo() (string, error) {
  ctx := &passlib.Context{
    Schemes: []abstract.Scheme{
      argon2.Crypter,
    },
  }

  return ctx.Hash("foo")
}

```
